# Generated by Django 5.1.7 on 2025-03-21 19:41
from django.utils.timezone import now

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='verified',
        ),
        migrations.AddField(
            model_name='points',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='points',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='points',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date'),
        ),
    ]
