# Generated by Django 5.1.7 on 2025-04-05 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_notificationtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date'),
        ),
    ]
