# Generated by Django 5.1.4 on 2025-01-02 19:53

import django.db.models.deletion
import rating.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_car_number', models.CharField(max_length=9, unique=True, validators=[rating.utils.validate_ug_plate_format])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_conflicted', models.BooleanField(default=False)),
                ('motor_type', models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score_anonymous', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('average_score_registered', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('average_score_verified', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('motor_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='rating.motorcar')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Anonymous', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('motor_type', models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster')], max_length=50)),
                ('system_comments', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motor_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_ratings', to='rating.motorcar')),
            ],
        ),
        migrations.CreateModel(
            name='MotorCarConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_type', models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motor_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='rating.motorcar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Anonymous', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating Score')),
                ('motor_type', models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster')], max_length=50)),
                ('system_comments', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motor_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.motorcar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
