# Generated by Django 5.1.4 on 2025-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster')], max_length=50, verbose_name='Motor Type'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='system_comments',
            field=models.TextField(verbose_name='System Comment'),
        ),
    ]
