# Generated by Django 5.1.4 on 2025-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_comment_alter_rating_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedrating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster'), ('Tuku', 'Tuku Tuku')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcar',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster'), ('Tuku', 'Tuku Tuku')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcarconflict',
            name='reported_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster'), ('Tuku', 'Tuku Tuku')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Private Car'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('truck', 'Truck'), ('Coaster', 'Coaster'), ('Tuku', 'Tuku Tuku')], max_length=50, verbose_name='Motor Type'),
        ),
    ]
