# Generated by Django 5.1.4 on 2025-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_archivedrating_motor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedrating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcar',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcarconflict',
            name='reported_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50, verbose_name='Motor Type'),
        ),
    ]
