# Generated by Django 5.1.4 on 2025-01-04 20:53

import rating.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_archivedrating_motor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedrating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcar',
            name='motor_car_number',
            field=models.CharField(max_length=12, unique=True, validators=[rating.utils.validate_ug_plate_format]),
        ),
        migrations.AlterField(
            model_name='motorcar',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcarconflict',
            name='reported_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='motor_type',
            field=models.CharField(choices=[('motorcycle', 'Boda Boda'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('taxi', 'Taxi'), ('tuku', 'Tuku Tuku'), ('coaster', 'Coaster')], max_length=50, verbose_name='Motor Type'),
        ),
    ]
