# Generated by Django 5.1.4 on 2025-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_alter_archivedrating_motor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerating',
            name='last_comments_anonymous',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='last_comments_registered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='last_comments_verified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='number_of_ratings_anonymous',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='number_of_ratings_registered',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='number_of_ratings_verified',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='top_three_system_comments_anonymous',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='top_three_system_comments_registered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='top_three_system_comments_verified',
            field=models.TextField(blank=True, null=True),
        ),
    ]
