# Generated by Django 5.1.4 on 2025-01-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_averagerating_last_comments_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerating',
            name='date_last_comments_anonymous',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='date_last_comments_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='date_last_comments_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
