# Generated by Django 5.1.4 on 2025-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_averagerating_date_last_comments_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerating',
            name='frequent_location_anonymous',
            field=models.CharField(default=1, max_length=255, verbose_name='Frequent Location Anonymous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagerating',
            name='frequent_location_registered',
            field=models.CharField(default=1, max_length=255, verbose_name='Frequent Location Registered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagerating',
            name='frequent_location_verified',
            field=models.CharField(default=1, max_length=255, verbose_name='Frequent Location Verified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagerating',
            name='last_location_anonymous',
            field=models.CharField(default=1, max_length=255, verbose_name='Last Location Anonymous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagerating',
            name='last_location_registered',
            field=models.CharField(default=1, max_length=255, verbose_name='Last Location Registered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averagerating',
            name='last_location_verified',
            field=models.CharField(default=1, max_length=255, verbose_name='Last Location Verified'),
            preserve_default=False,
        ),
    ]
