# Generated by Django 5.1.4 on 2025-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_averagerating_frequent_location_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='frequent_location_anonymous',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Frequent Location Anonymous'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='frequent_location_registered',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Frequent Location Registered'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='frequent_location_verified',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Frequent Location Verified'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='last_location_anonymous',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Location Anonymous'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='last_location_registered',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Location Registered'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='last_location_verified',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Location Verified'),
        ),
    ]
