# Generated by Django 5.1.4 on 2025-01-05 15:20

import rating.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_alter_averagerating_frequent_location_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcar',
            name='motor_car_number',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[rating.utils.validate_ug_plate_format]),
        ),
    ]
