# Generated by Django 5.1.4 on 2025-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0011_alter_motorcar_motor_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='system_comments',
            field=models.TextField(blank=True, null=True, verbose_name='System Comment'),
        ),
    ]
