# Generated by Django 5.1.4 on 2025-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_alter_rating_system_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='system_comments',
            field=models.TextField(default=1, verbose_name='System Comment'),
            preserve_default=False,
        ),
    ]
