# Generated by Django 5.1.4 on 2025-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_alter_rating_system_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
    ]
