# Generated by Django 5.1.4 on 2025-02-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0014_alter_rating_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
