# Generated by Django 5.2.1 on 2025-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0015_alter_rating_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_method',
            field=models.CharField(default='Text', max_length=25, verbose_name='Method Used'),
        ),
    ]
