# Generated by Django 5.1.4 on 2025-01-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Registered', 'Registered'), ('Verified', 'Verified')], default='User', max_length=50, verbose_name='User Type'),
        ),
    ]
