# Generated by Django 5.1.4 on 2025-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='other_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
