# Generated by Django 5.1.4 on 2025-01-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number_sec',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Second Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Primary Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Other Names'),
        ),
    ]
