# Generated by Django 5.1.4 on 2025-01-13 21:09

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_contact_number_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[accounts.utils.normalize_phone_number_model]),
        ),
    ]
