# Generated by Django 5.1.4 on 2025-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_current_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Registered', 'Registered'), ('Verified', 'Verified')], default='Registered', max_length=50, verbose_name='User Type'),
        ),
    ]
